# Builds the delta update installer: the files changed since $FromVersion (per its manifest.json),
# plus deletions, wrapped by delta.iss with a version guard. Run AFTER package.ps1, which publishes
# publish\win-x64 and writes installer\manifest.json for the current build.
#
# Usage: pwsh -File package-delta.ps1 -FromVersion 1.2 -ToVersion 1.3 -PrevManifest prevrel\manifest.json
#
# On success, writes installer\<delta>.exe and installer\delta-info.json { from, asset }.
param(
    [Parameter(Mandatory)] [string]$FromVersion,   # previous release version, e.g. "1.2" / "1.2-beta"
    [Parameter(Mandatory)] [string]$ToVersion,     # this release version
    [Parameter(Mandatory)] [string]$PrevManifest   # path to the previous release's manifest.json
)
$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$publishRel = "publish\win-x64"
$installerDir = Join-Path $root "installer"
$currManifest = Join-Path $installerDir "manifest.json"

if (-not (Test-Path $currManifest)) { throw "current manifest not found ($currManifest); run package.ps1 first" }
if (-not (Test-Path $PrevManifest)) { throw "previous manifest not found ($PrevManifest)" }

# Load both manifests into hashtables (path -> sha256).
function Read-Files($path) {
    $map = @{}
    foreach ($p in (Get-Content -LiteralPath $path -Raw | ConvertFrom-Json).files.PSObject.Properties) {
        $map[$p.Name] = $p.Value
    }
    return $map
}
$prev = Read-Files $PrevManifest
$curr = Read-Files $currManifest

# Changed/new = current files whose hash differs from prev (or that prev didn't have).
# Deleted = prev files no longer present.
$changed = @($curr.Keys | Where-Object { -not $prev.ContainsKey($_) -or $prev[$_] -ne $curr[$_] } | Sort-Object)
$deleted = @($prev.Keys | Where-Object { -not $curr.ContainsKey($_) } | Sort-Object)
Write-Host "==> Delta $FromVersion -> $ToVersion : $($changed.Count) changed/new, $($deleted.Count) deleted" -ForegroundColor Cyan

# Generate installer\delta-files.iss ([Files] for changed/new, [InstallDelete] for removed).
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("; Generated by package-delta.ps1 — do not edit.")
[void]$sb.AppendLine("[Files]")
foreach ($rel in $changed) {
    $win = $rel -replace '/', '\'
    $dir = Split-Path $win -Parent
    $destSub = if ($dir) { "\$dir" } else { "" }
    [void]$sb.AppendLine("Source: `"$publishRel\$win`"; DestDir: `"{app}$destSub`"; Flags: ignoreversion")
}
[void]$sb.AppendLine("")
[void]$sb.AppendLine("[InstallDelete]")
foreach ($rel in $deleted) {
    $win = $rel -replace '/', '\'
    [void]$sb.AppendLine("Type: files; Name: `"{app}\$win`"")
}
Set-Content -LiteralPath (Join-Path $installerDir "delta-files.iss") -Value $sb.ToString() -Encoding utf8

# Locate the Inno Setup compiler (same as package.ps1).
$iscc = @(
    "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
    "${env:ProgramFiles}\Inno Setup 6\ISCC.exe"
) | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $iscc) { $iscc = (Get-Command ISCC.exe -ErrorAction SilentlyContinue).Source }
if (-not $iscc) { throw "ISCC.exe not found. Install Inno Setup 6.3+ from https://jrsoftware.org/isdl.php" }

Write-Host "==> Compiling delta installer ($FromVersion -> $ToVersion)" -ForegroundColor Cyan
& $iscc "/DMyAppVersion=$ToVersion" "/DFromVersion=$FromVersion" (Join-Path $root "delta.iss")
if ($LASTEXITCODE -ne 0) { throw "delta Inno Setup compile failed" }

# delta.iss OutputBaseFilename = TextTemplateManager-Update-<from>-to-<to>
$asset = "TextTemplateManager-Update-$FromVersion-to-$ToVersion.exe"
if (-not (Test-Path (Join-Path $installerDir $asset))) { throw "expected delta not produced: $asset" }

[ordered]@{ from = $FromVersion; asset = $asset } | ConvertTo-Json |
    Set-Content -LiteralPath (Join-Path $installerDir "delta-info.json") -Encoding utf8
Write-Host "==> Delta installer: installer\$asset" -ForegroundColor Green
